import type { Stream, Streamer, ChatMessage } from '@/lib/types'

export const mockStreamers: Record<string, Streamer> = {
  user1: {
    id: 'user1',
    username: 'Alex Chen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    followers: 5240,
    bio: 'Full-time streamer | Gaming & IRL',
  },
  user2: {
    id: 'user2',
    username: 'Jordan Dev',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan',
    followers: 3890,
    bio: 'Web development & coding tutorials',
  },
  user3: {
    id: 'user3',
    username: 'Sam Music',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sam',
    followers: 7650,
    bio: 'Live music producer & DJ',
  },
  user4: {
    id: 'user4',
    username: 'Casey Art',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Casey',
    followers: 2340,
    bio: 'Digital art & design streams',
  },
  user5: {
    id: 'user5',
    username: 'Morgan Games',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Morgan',
    followers: 9120,
    bio: 'Competitive gaming & esports',
  },
}

export const mockStreams: Stream[] = [
  {
    id: '1',
    title: 'Building a React Performance Dashboard',
    description: 'Learning React optimization techniques in real-time',
    thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=320&h=180&fit=crop',
    streamer: mockStreamers.user2,
    viewers: 1240,
    duration: '2h 15m',
    category: 'Development',
    isLive: true,
    tags: ['react', 'web-dev', 'tutorial'],
  },
  {
    id: '2',
    title: 'Late Night Gaming Session',
    description: 'Competitive ranked matches and chill vibes',
    thumbnail: 'https://images.unsplash.com/photo-1538481143081-127f84b1a54d?w=320&h=180&fit=crop',
    streamer: mockStreamers.user5,
    viewers: 3420,
    duration: '4h 30m',
    category: 'Gaming',
    isLive: true,
    tags: ['gaming', 'esports', 'ranked'],
  },
  {
    id: '3',
    title: 'Ambient Music Production Session',
    description: 'Creating experimental electronic music',
    thumbnail: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=320&h=180&fit=crop',
    streamer: mockStreamers.user3,
    viewers: 892,
    duration: '1h 45m',
    category: 'Music',
    isLive: true,
    tags: ['music', 'production', 'electronic'],
  },
  {
    id: '4',
    title: 'Digital Illustration Masterclass',
    description: 'Creating professional digital artwork from scratch',
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=320&h=180&fit=crop',
    streamer: mockStreamers.user4,
    viewers: 567,
    duration: '3h 00m',
    category: 'Art & Design',
    isLive: false,
    tags: ['art', 'design', 'tutorial'],
  },
  {
    id: '5',
    title: 'IRL City Exploration Adventure',
    description: 'Exploring hidden gems in the city',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=320&h=180&fit=crop',
    streamer: mockStreamers.user1,
    viewers: 2150,
    duration: '1h 30m',
    category: 'IRL',
    isLive: true,
    tags: ['irl', 'adventure', 'travel'],
  },
  {
    id: '6',
    title: 'Advanced TypeScript Patterns',
    description: 'Deep dive into TypeScript advanced features',
    thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=320&h=180&fit=crop',
    streamer: mockStreamers.user2,
    viewers: 1890,
    duration: '2h 00m',
    category: 'Development',
    isLive: true,
    tags: ['typescript', 'programming', 'web-dev'],
  },
  {
    id: '7',
    title: 'Creative Coding Experiments',
    description: 'Trying out creative coding libraries and techniques',
    thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=320&h=180&fit=crop',
    streamer: mockStreamers.user1,
    viewers: 945,
    duration: '1h 20m',
    category: 'Development',
    isLive: false,
    tags: ['coding', 'creative', 'javascript'],
  },
  {
    id: '8',
    title: 'Tournament Finals - Grand Stage',
    description: 'Live tournament finals with professional players',
    thumbnail: 'https://images.unsplash.com/photo-1538481143081-127f84b1a54d?w=320&h=180&fit=crop',
    streamer: mockStreamers.user5,
    viewers: 8920,
    duration: '5h 45m',
    category: 'Esports',
    isLive: true,
    tags: ['esports', 'tournament', 'gaming'],
  },
]

export const mockChatMessages: ChatMessage[] = [
  {
    id: '1',
    author: 'Viewer1',
    authorId: 'v1',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=v1',
    content: 'Great stream! Love the content',
    timestamp: new Date(Date.now() - 5 * 60000),
    color: 'hsl(270 100% 55%)',
  },
  {
    id: '2',
    author: 'Viewer2',
    authorId: 'v2',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=v2',
    content: 'How do you approach performance optimization?',
    timestamp: new Date(Date.now() - 4 * 60000),
    color: 'hsl(173 58% 39%)',
  },
  {
    id: '3',
    author: 'Viewer3',
    authorId: 'v3',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=v3',
    content: 'This is so helpful, thanks!',
    timestamp: new Date(Date.now() - 3 * 60000),
    color: 'hsl(43 74% 66%)',
  },
  {
    id: '4',
    author: 'Viewer4',
    authorId: 'v4',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=v4',
    content: 'Can you share the code?',
    timestamp: new Date(Date.now() - 2 * 60000),
    color: 'hsl(27 87% 67%)',
  },
]
